### ISSUE TITLE
Issues with iem_fung92_interface

### ISSUE THREAD

**Issue by easihene** [smrt-model/smrt#10]
Hello, 

I'm trying to implement "iem_fung92" interface in my medium but SMRTError raised an exception as "Parameter roughness_rms must be specified" even though I specified it.

Here is the code:
```
temperature = 273 - 15
brine_volume_fraction=[0.15]
corr_length = [5e-3]
roughness_rms=[0.4]

ic = make_ice_column('firstyear', thickness=[0.5], microstructure_model='exponential', interface="iem_fung92",
                     temperature=temperature, brine_volume_fraction=brine_volume_fraction, roughness_rms=roughness_rms, corr_length=corr_length, add_water_substrate=True)

SMRTError: Parameter roughness_rms must be specified

```
Please advise on what I doing wrong.

Thanks!

**Comment by JulienMeloche** [comment]
Hi,

I'm not used to sea ice modelling with SMRT but it seems your problem comes from the corr length of the ice. It expect a corr length of the ice phase when using the exponential microstructure model. You could make it work by removing the interface and roughness_rms in make_ice_column. I've specify here that you need a different corr_length.
```
corr_length_micro_ice = 5e-5
ice = make_ice_column('firstyear', thickness=[0.5], microstructure_model='exponential',
                                        temperature=temperature, brine_volume_fraction=brine_volume_fraction, 
                                        corr_length=corr_length_micro_ice, add_water_substrate=True)
```

Then, you could specify the rough interface of the surface using this

```
ice.interfaces[0] = make_interface('iem_fung92', roughness_rms=0.4, corr_length=5e-3)
```

It works fine on my machine using corr_length_micro_ice = 5e-5 but I don't know which value you should use...

**Comment by ghislainp** [comment]
@JulienMeloche's answer is correct. make_interface must be used for the interface models requiring parameters (all the rough interface models indeed require some parameters. Flat or Transparent are example of interface models without parametres) and we have used this two-step technique to set the surface interface only so far. 

But it is not convenient. With @mjsandells  and Justin Murfitt we discussed about how to set the surface roughness more easily because setting the surface roughness is very common compare to setting internal interfaces. It was decided to add a "surface" argument in make_snowpack and make_ice_column, similar to the "substrate" argument. This is now implemented.

The recommended way to set the surface interface is now:

```
ice = make_ice_column('firstyear', thickness=[0.5], microstructure_model='exponential',
                                        temperature=temperature, brine_volume_fraction=brine_volume_fraction, 
                                        corr_length=corr_length_micro_ice, add_water_substrate=True,
                                        surface=make_interface('iem_fung92', roughness_rms=0.4, corr_length=5e-3))
```

The documentation is (should be updated soon): 
https://smrt.readthedocs.io/en/latest/smrt.inputs.make_medium.html

Another point, be careful with rough interface models, the numerical stability is so so. You may need advice interpret your results.

**Comment by easihene** [comment]
Hi Julien and Ghis,

Both advice worked perfectly well. All the best!
